package com.pl.kasia.services;


import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;


import studia.Student;




public class StudentDBManager {

	
	private Connection conn;

	private Statement stmt;

	private PreparedStatement addStudentStmt;
	private PreparedStatement getStudentStmt;

	private boolean add;

	
	
	public StudentDBManager()
	{
		try {
			

			conn= DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");

			stmt=conn.createStatement();
			boolean studentTableExists=false;

			ResultSet rs= conn.getMetaData().getTables(null, null, null, null);

			while(rs.next())
			{
				if("Student".equalsIgnoreCase(rs.getString("TABLE_IMIE")))
					{
						studentTableExists=true;
						break;
					}
			}


			if(!studentTableExists)
			{
				stmt.executeUpdate("" +
					"CREATE TABLE student(" +
					"ID bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
					"name varchar(20)," +
					"" +
					")");
			}

			addStudentStmt=conn.prepareStatement("" +
					"INSERT INTO student (name) VALUES (?)" +
					"");

			getStudentStmt=conn.prepareStatement("" +
					"SELECT * FROM student" +
					"");



		} catch (SQLException e) {

			e.printStackTrace();
		}
	}

	public void addStudent(Student s)
	{
		try {
			addStudentStmt.setString(1, s.getImie());

			addStudentStmt.executeUpdate();

		} catch (SQLException e) {

			e.printStackTrace();
		}

	}

	public List<Student> getAllStudent()
	{
		List<Student> student=new ArrayList<Student>();

		try {
			ResultSet rs= getStudentStmt.executeQuery();

			while(rs.next())
			{
				
			 student.add(new Student(rs.getString("Imie"), null, null));
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return student;
	}



	
}
